#!/bin/bash
#
#  curl commands to reload the data from the previous tutorial
#
#

set -e

printf "⏳ Loading context data "

 curl -iX POST \
  'http://localhost:1026/v2/entities' \
  -H 'Content-Type: application/json' \
  -d '
{
    "id": "urn:ngsi-ld:Lab:001",
    "type": "Lab",
    "address": {
        "type": "PostalAddress",
        "value": {
            "streetAddress": "Gençlik Bulvarı",
            "addressRegion": "Eskişehir",
            "addressLocality": "Eskişehir Osmangazi Üniversitesi",
            "postalCode": "26040"
        },
        "metadata": {
            "verified": {
                "value": true,
                "type": "Boolean"
            }
        }
    },
    "location": {
        "type": "geo:json",
        "value": {
             "type": "Point",
             "coordinates": [39.74928562191364,30.48216550271973]
        }
    },
    "name": {
        "type": "Text",
        "value": "ASIST"
    }
}'


curl -iX POST \
  'http://localhost:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -d '{
  "actionType":"APPEND",
  "entities":[
    {
      "id":"urn:ngsi-ld:Motor:unit001", "type":"Motor",
      "location":{
        "type":"geo:json", "value":{ "type":"Point","coordinates":[39.74928562191364,30.48216550271973]}
      },
      "name":{
        "type":"Text", "value":"Motor1"
      },
      "vibrationSensorCount":{
        "type":"Integer", "value":1
      }
    },
    {
      "id":"urn:ngsi-ld:Motor:unit002", "type":"Motor",
      "location":{
        "type":"geo:json","value":{"type":"Point","coordinates":[39.74928562191364,30.48216550271973]}
      },
      "name":{
        "type":"Text", "value":"Motor2"
      },
      "vibrationSensorCount":{
        "type":"Integer", "value":1
      }
    }
  ]
}'


curl -iX POST \
  'http://localhost:4041/iot/services' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "services": [
   {
     "apikey":      "4jggokgpepnvsb2uv4s40d59ov",
     "cbroker":     "http://orion:1026",
     "entity_type": "Thing",
     "resource":    "/iot/json"
   }
 ]
}'


curl -iX POST \
  'http://localhost:4041/iot/devices' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "devices": [
   {
     "device_id":   "vibrationSensor001",
     "entity_name": "urn:ngsi-ld:VibrationSensor:001",
     "entity_type": "VibrationSensor",
     "timezone":    "Europe/Berlin",
     "attributes": [
       { "object_id": "MIN_x", "name": "MIN_x", "type": "Number" },
       { "object_id": "MIN_y", "name": "MIN_y", "type": "Number" },
       { "object_id": "MIN_z", "name": "MIN_z", "type": "Number" },
       { "object_id": "MAX_x", "name": "MAX_x", "type": "Number" },
       { "object_id": "MAX_y", "name": "MAX_y", "type": "Number" },
       { "object_id": "MAX_z", "name": "MAX_z", "type": "Number" },
       { "object_id": "MEAN_x", "name": "MEAN_x", "type": "Number" },
       { "object_id": "MEAN_y", "name": "MEAN_y", "type": "Number" },
       { "object_id": "MEAN_z", "name": "MEAN_z", "type": "Number" },
       { "object_id": "RMS_x", "name": "RMS_x", "type": "Number" },
       { "object_id": "RMS_y", "name": "RMS_y", "type": "Number" },
       { "object_id": "RMS_z", "name": "RMS_z", "type": "Number" },
       { "object_id": "STD_x", "name": "STD_x", "type": "Number" },
       { "object_id": "STD_y", "name": "STD_y", "type": "Number" },
       { "object_id": "STD_z", "name": "STD_z", "type": "Number" },
       { "object_id": "SKEW_x", "name": "SKEW_x", "type": "Number" },
       { "object_id": "SKEW_y", "name": "SKEW_y", "type": "Number" },
       { "object_id": "SKEW_z", "name": "SKEW_z", "type": "Number" },
       { "object_id": "KURT_x", "name": "KURT_x", "type": "Number" },
       { "object_id": "KURT_y", "name": "KURT_y", "type": "Number" },
       { "object_id": "KURT_z", "name": "KURT_z", "type": "Number" }
     ],
     "static_attributes": [
       { "name":"refMotor", "type": "Relationship", "value": "urn:ngsi-ld:Motor:unit001"}
     ]
   }
 ]
}
'


curl -iX POST \
  'http://localhost:7896/iot/json?k=4jggokgpepnvsb2uv4s40d59ov&i=vibrationSensor001' \
  -H 'Content-Type: application/json' \
  -d '[{"MIN_x": 0.18628},{"MIN_y": 0.187838},{"MIN_z": 0.123737},{"MAX_x": 0.1172893898},{"MAX_y": 0.316486473},{"MAX_z": 0.13685863},{"MEAN_x": 0.11534578},{"MEAN_y": 0.1345346},{"MEAN_z": 0.314747},{"RMS_x": 0.136236},{"RMS_y": 0.145734},{"RMS_z": 0.81628},{"STD_x": 0.187838},{"STD_y": 0.123737},{"STD_z": 0.1172893898},{"SKEW_x": 0.1316486473},{"SKEW_y": 0.131685863},{"SKEW_z": 0.11534578},{"KURT_x": 0.1345346},{"KURT_y": 0.134747},{"KURT_z": 0.136236}]'
  
  
  curl -X GET \
  'http://localhost:1026/v2/entities/urn:ngsi-ld:VibrationSensor:001?type=VibrationSensor' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /'
  
  
  
  curl -iX POST \
  'http://localhost:1026/v2/subscriptions/' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
  "description": "Notify QuantumLeap of count changes of any Vibration Sensor",
  "subject": {
    "entities": [
      {
        "idPattern": "VibrationSensor.*"
      }
    ],
    "condition": {
      "attrs": [
       "maxx",
	"MIN_x",
    "MIN_y",
    "MIN_z",
    "MAX_x",
    "MAX_y",
    "MAX_z",
    "MEAN_x",
    "MEAN_y",
    "MEAN_z",
    "RMS_x", 
    "RMS_y",
    "RMS_z",
    "STD_x",
    "STD_y",
    "STD_z",
    "SKEW_x",
    "SKEW_y",
    "SKEW_z",
    "KURT_x",
    "KURT_y",
    "KURT_z"
    ]
    }
  },
  "notification": {
    "http": {
      "url": "http://quantumleap:8668/v2/notify"
    },
    "attrs": [
      "MIN_x",
        "MIN_y",
        "MIN_z",
        "MAX_x",
        "MAX_y",
        "MAX_z",
        "MEAN_x",
        "MEAN_y",
        "MEAN_z",
        "RMS_x", 
        "RMS_y",
        "RMS_z",
        "STD_x",
        "STD_y",
        "STD_z",
        "SKEW_x",
        "SKEW_y",
        "SKEW_z",
        "KURT_x",
        "KURT_y",
        "KURT_z"
    ],
    "metadata": ["dateCreated", "dateModified"]
  },
  "throttling": 1
}'


curl -iX POST \
  'http://localhost:7896/iot/json?k=4jggokgpepnvsb2uv4s40d59ov&i=vibrationSensor001' \
  -H 'Content-Type: application/json' \
  -d '[{"MIN_x": 1},{"MIN_y": 0.9},{"MIN_z": 0.2},{"MAX_x": 0.4},{"MAX_y": 1},{"MAX_z": 0.6},{"MEAN_x": 0.77},{"MEAN_y": 0.76},{"MEAN_z": 0.1},{"RMS_x": 1},{"RMS_y": 1},{"RMS_z": 1},{"STD_x": 1},{"STD_y":1},{"STD_z": 0.8},{"SKEW_x": 0.6},{"SKEW_y": 0.7},{"SKEW_z": 1},{"KURT_x": 0.66},{"KURT_y": 0.66},{"KURT_z": 0.166}]'
  
  
echo -e " \033[1;32mdone\033[0m"
